stages:
  - mirror

mirror_repository:
  stage: mirror
  only:
    - main
  script:
    - apt-get update -qq && apt-get install -y git
    - git config --global user.email "abijuru@rhrk.uni-kl.de"
    - git config --global user.name "jeph864"
    - git remote add github https://github.com/jeph864/cemtom.git
    - 'git push --mirror https://${GITHUB_TOKEN}@https://github.com/jeph864/cemtom.git'

