stages:
  - mirror

mirror_repository:
  stage: mirror
  only:
    - main
  script:
    - apt-get update -qq && apt-get install -y git
    - git config --global user.email "abijuru@rhrk.uni-kl.de"
    - git config --global user.name "jeph864"
    - 'git remote remove github || true'
    - git remote add github https://${GITHUB_TOKEN}@github.com/jeph864/cemtom.git
    - git fetch origin main
    - git push github refs/heads/main:refs/heads/gmain

